application:
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "test@gmail.com"
  authorization_token: "8cbb8de2-efa7-4ebe-a528-8f7f4ab76eef"
  timeout_milliseconds: 10000